config:
  ## The datasource properties on config are passed through helm tpl function.
  ## ref: https://helm.sh/docs/developing_charts/#using-the-tpl-function
  datasource:
    # Specify one of both datasource or datasourceSecret
    host: '172.19.0.2'
    user: postgres
    password: 960WAQzfGd

serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: true
  labels: 
    release: grafana

